### ISSUE TITLE
Suggestions for nimterop

### ISSUE THREAD

**Issue by genotrance** [sstadick/nimedlib#2]
Great work getting this to work with nimterop. Some suggestions:-

- Instead of using `nimteropBuildDir()`, would be better to have a path relative to your project using `currentSourcePath.parentDir()`.
- Remove `cDisableCaching()` so that users of your lib don't have to regenerate it every time they compile their project. It only makes sense during dev. of the lib.
- You don't need either `cAddStdDir("cpp")` or `cAddSearchDir(baseDir)`.

**Comment by sstadick** [comment]
Thanks for these suggestions! I have heeded them all. Again, nimterop is awesome! I will certainly be using it more in the future.
